apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: grumpy-kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
#    volumes:
#      - id: 0
#        type: persistent-claim
#        size: 100Gi
#        deleteClaim: false
#        kraftMetadata: shared