apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: "Quarkus GrumpyCat"
  labels:
    kubernetes.io/metadata.name: grumpycat
  name: grumpycat
spec:
  finalizers:
  - kubernetes
